### ISSUE TITLE
Booting from CP/M 86 disk fails

### ISSUE THREAD

**Issue by Waffle2** [andreas-jonsson/virtualxt#15]
The my image boots fine under virtualbox, but I really want to work with the V20 emulation that virtualxt offers.

When I attempt to boot from this image, I get a pop-up:

"The selected disk is not bootable."

A copy of the file is available at https://ufile.io/piiuu41b

**Comment by Waffle2** [comment]
I did modify the checkBootsector code to always return true to bypass the boot sector validation code (since CP/M doesn't use that), and was able to partially boot up.  I suspect there are some more issues...

**Comment by Waffle2** [comment]
Ah.  Problem resolved - the modified CP/M 86 disk had a few AT specific commands being run, and this caused it to fail.

So, just the checkBootsector code should be modified, I think.

**Comment by Waffle2** [comment]
Damn.  Spoke too soon.  Running nearly any command seems to cause the system to hang.  Not quite sure what's up...

**Comment by Waffle2** [comment]
The problem appears to be the lack of an interrupt.  Based on my hasty use of your built-in debugger (thank you!), CPM does a disk reset, then appears to wait for an interrupt with a HLT instruction.  Since the interrupt never comes, the program hard hangs.  I commented out the setting of the halt state in the decoder, and that allowed me to boot from floppy, then format the hard drive, install the system onto the drive, then boot from the hard disk.

I'll dig into it further over the coming days. 

Again, thank you for writing this!

**Comment by andreas-jonsson** [comment]
Hi!

Thank you for trying this out. :)

**Comment by Waffle2** [comment]
A minor fix:  The V20/V30 'optimized' the AAD instruction by ignoring the supplied immediate multiplier.  Later version of the X86 documented this, and others now use AAD 16, for example.  The V20/V30 always assume that it is 10.

 975         case 0xD5: // AAD *d8
 976                 if !p.isV20 {
 977                     p.SetAX((uint16(p.AL()) + uint16(p.AH())*uint16(p.readOpcodeStream())) & 0xFF)
 978                 } else {
 979                     p.readOpcodeStream()
 980                     p.SetAX((uint16(p.AL()) + uint16(p.AH())*10) & 0xFF)
 981                 }
 982                 p.updateFlagsSZP16(p.AX())

**Comment by andreas-jonsson** [comment]
Thanks for catching this.
I will push an update.

**Comment by Waffle2** [comment]
Thank you!  Working through another v20 issue, I had a brief question... did you implement the 8080 side of the v20?  I am having a problem when I switch into V20 emulation mode...

**Comment by Waffle2** [comment]
There is another V20 incompatibility.  The shift instructions on the V20 do not mask to the lower 5 bits, but the 8088 does.`

`
--- a/emulator/processor/cpu/rot.go
+++ b/emulator/processor/cpu/rot.go
@@ -139,7 +139,7 @@ func (p *CPU) shiftOrRotate8(op, a, b byte) byte {
                return a
        }
 
-       if p.isV20 {
+       if !p.isV20 {
                b &= 0x1F
        }

`

Yes, the 186/188 does not mask.

It also appears that several other NEC instructions are not present - for example, the ROL4 r/m8.  
I can certainly add them if you wish.

**Comment by andreas-jonsson** [comment]
So... currently I'm working on a complete rewrite of the emulator. (The 0.7 branch)
I'm developing it using this tool I built for [validation](https://hackaday.io/project/184209-virtualxt-hardware-validator).

I did not intend to keep the V20 code but instead working towards 80286/AT support.
But if this is something you would like and be willing to help support/fix I would consider keeping it.

(There is no 8080 support in the V20 code right now.)

**Comment by Waffle2** [comment]
Since it is one of the only emulators that even suggests that it supports V20, yes, I'm quite interested.  I will be able to fix and validate code, and compare it to real hardware for both 8088 and V20 systems.  I do have a 286 system in storage as well, so can help on that at the appropriate time...

**Comment by andreas-jonsson** [comment]
Oho.. that's cool.
I have zero experience with V20 systems so if you would like to help with that it would be fantastic.
Another thing I have on my todo list is VGA support. If that is something that is of interest to you.

I hope that the 0.7 branch will be "on pair" with the current version within a week or two. (Probable take a bit longer for the minor bells and whistles.)

I will move the current V20 code over to the 0.7 version then.

**Comment by Waffle2** [comment]
You bet.  I'll get started on the 8080 code, then.   For me, the CPU emulation is the most important (and there are *lots* of little "gotcha's" between the 8088, v20 and 80286 that I've run into over the years).

**Comment by andreas-jonsson** [comment]
I have added a build option for V20 CPUs in the 0.7 branch now.
You can build/run it using the following command in the project root `zig build -Dv20 run`.
There is currently no runtime switch for CPU type. I'll figure that out later.

`libvxt` is the emulator core and is written in C11 (without libc) and the peripheral, `libvxtp` is C11 (with libc) or Zig code.
The frontend (main.c) is linked with SDL2.

If you want to know more about how to set the toolchain up you can look in `.github/workflows/build.yml`.
(It is kind if straight forward both for Linux and Windows.)

I have not yet ported all of the excising V20 code from the old version but I should get to that shortly. :)
(you are welcome to assist if you want.)

**Comment by Waffle2** [comment]
I have it, and am starting to go through it.  I've already learned to hate zig :-)

**Comment by andreas-jonsson** [comment]
Yea.. I'm not 100% sure about either... yet. ;)

But the toolchain is kind of neat for C development I think.
It is also very nice to be able to cross-compile the C code to other platforms. (just like Go)

**Comment by andreas-jonsson** [comment]
Fyi.
I have moved the V20 code over from the old branch. Can't say it is very well tested though. :)
The 0xF two byte opcode is not implemented at all it it just throws invalid opcode for V20&286 for now.
Guess that's where a lot of work needs to be done for better compatibility.

(I also moved a lot of files around to make my IDE happy so merging might be messy if you have done changes.)

**Comment by andreas-jonsson** [comment]
@Waffle2 if you are still interested in helping out on the V20 front the new codebase is now in both the develop & the edge branch.

Could you share your CP/M floppy image? or share what version you where using?
It would be great to test it out on the new codebase.

**Comment by Waffle2** [comment]
> On Jun 7, 2022, at 5:04 AM, Andreas T Jonsson ***@***.***> wrote:
> 
> 
> @Waffle2 if you are still interested in helping out on the V20 front the new codebase is now in both the develop & the edge branch.
> 
> Could you share your CP/M floppy image? or share what version you where using?
> It would be great to test it out on the new codebase.


Sure.  I also picked up a real V20 board, and can test things against the hardware itself - yet another good thing :-)

hd.img is the “hard drive” image I used to test things, transfer.img is what I’ve been using to get files to and from the image.  

I expect you will have to fix the boot code to make the image work :-)

**Comment by andreas-jonsson** [comment]
This works just fine out of the box now with version 0.7 (develop & edge branch) so I'm going to close this now.
Feel free to open a new issue for the full V20 support.
