### ISSUE TITLE
Full V20 support

### ISSUE THREAD

**Issue by Waffle2** [andreas-jonsson/virtualxt#18]
The V20 support is not complete, and common utilities are not able to run v20 code.  I suspect the 8085 emulation is not working, either :-)

**Comment by andreas-jonsson** [comment]
Yes. That is correct.
I should probably not mention V20 since it is only the [186 instruction set](https://github.com/andreas-jonsson/virtualxt/issues/15#issuecomment-1106183013) that is supported.

This is not the main focus for me so fixing this is quite dependent on contribution. There is a V20 code path an separation in the emulator so it should be possible to add.

**Comment by Waffle2** [comment]
As mentioned, I purchased a V20 system exactly for this purpose.  Now that I have zig working on my system, and I'm able to compile the code, I'll be contributing to this.

**Comment by andreas-jonsson** [comment]
That's super exciting! Looking forward to it. :)

**Comment by andreas-jonsson** [comment]
Hi @Waffle2 how is it going?

Would you like me to send you a [hardware validator](https://hackaday.io/project/184209-virtualxt-hardware-validator) kit? 

You probably need to make some software adjustments to test the 8080 emulation but it should work in theory.
The hardest part is probably to find a RaspberryPI4 in this day and age unless you already have one. :)

**Comment by Waffle2** [comment]
I have all of the pi's, so not a problem for me :-) 

Please email me directly waffle_contest@gmail.com, and I'll send you my address.  I have sockets if you prefer to just mail the bare board...

**Comment by andreas-jonsson** [comment]
> I have all of the pi's, so not a problem for me :-)
> 
> Please email me directly [waffle_contest@gmail.com](mailto:waffle_contest@gmail.com), and I'll send you my address. I have sockets if you prefer to just mail the bare board...

I'm trying to send you an email to that address but it just bounces?

**Comment by Waffle2** [comment]
I don't know why.  Gmail is like that, though.  I sent you my address via paypal.  If you don't get it, let me know.

**Comment by Torinde** [comment]
> it is only the 186 instruction set that is supported.

I think then it's fine to label that 186 (there were PC clones using 186/188 CPUs actually) - and add another V20 when more of the V20 features get implemented.

**Comment by andreas-jonsson** [comment]
Yea, true.
It should be noted though, that the opcodes that are implemented follows the behavior of the NEC V20 and not the Intel 80186.
So in a way it is more like an unfinished V20 rather then a 186.

It is likely the V20 code path will be dropped in the next major iteration unless there is a contribution from someone. :(

**Comment by Torinde** [comment]
Oh, that'll be a pity - I would rather keep it incomplete (so that someone can potentially expand on it) rather than drop it.

**Comment by andreas-jonsson** [comment]
> Oh, that'll be a pity - I would rather keep it incomplete (so that someone can potentially expand on it) rather than drop it.

Well. That release might be years, so there is still time. :D
Soon there should be comprehensive [V20 tests](https://github.com/TomHarte/ProcessorTests) available as well.

**Comment by andreas-jonsson** [comment]
Not a goal any more.

**Comment by Torinde** [comment]
> unless there is a contribution from someone

Maybe you can share some code from MartyPC:
- https://github.com/dbalsom/martypc/discussions/109#discussioncomment-9720314

**Comment by andreas-jonsson** [comment]
Well. Marty is written in Rust so it is a bit hard to just share.

There was a fair bit of V20/286 support in VirtualXT 1.0. But It has now been removed in favor of making the code easier to understand and more lightweight.

This was one of the main goals of the project initially and I have decided to refocus on simplicity instead of features.
