### ISSUE TITLE
Interrupts not working correctly

### ISSUE THREAD

**Issue by Waffle2** [andreas-jonsson/virtualxt#19]
To replicate, start CPM-86.  Note the time on the bottom of the screen updating.
Then, run newtod.  Change the date and time - the new time is recorded correctly in the system, but the display stops updating.

This works correctly under Virtualbox.

**Comment by andreas-jonsson** [comment]
I wonder if this has something to do with the minimalistic RTC implementation.
Can I test this with the CPM image you gave me earlier?

**Comment by Waffle2** [comment]
Yes, you can.  In fact, running any program will cause the RTC to stop - you don't have to use the newtod program.

**Comment by andreas-jonsson** [comment]
Fixed develop.

I think there is also problem with the way keyboard input gets buffered. It's causes the keys to feel "mushy".
That however is unrelated to the clock issue.

**Comment by Waffle2** [comment]
Confirmed, and yes the keyboard input is irregular.  I had assumed it was related to the interrupts, but it's still sluggish.

**Comment by andreas-jonsson** [comment]
I have done some adjustments that makes it a bit better. But it still is not perfect in CPM.
Will open a separate issue because I need to look in to how CPMs IRS for the keyboard works exactly.
