### ISSUE TITLE
CPU Validator

### ISSUE THREAD

**Issue by andreas-jonsson** [andreas-jonsson/virtualxt#2]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%241,000%20Funded-%2300A156.svg" />](https://issuehunt.io/r/andreas-jonsson/virtualxt/issues/2)

Create a CPU validator which compares the instruction execution with Bochs.

The author of [nxvm](https://github.com/cshaxu/nxvm) wrote a validation tool which does this named "BochX".
He recently re-licensed the BochX tool under the BSD license.
Of note, BochX's patch for Bochs is supposed to be against Bochs 2.6, however,
it looks like it was actually written against an earlier pre-release version of Bochs 2.6.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $1,000.00)

- $1,000.00 have been anonymously funded.
### Submitted pull Requests
- [#14 CPU Validator](https://issuehunt.io/r/andreas-jonsson/virtualxt/pull/14)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/andreas-jonsson/virtualxt/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by andreas-jonsson** [comment]
The requirements are not that fixed.

It should exercise the majority of the 8088 instruction set and validate it again a known good source.
The validator needs to tap in to the emulator in a clean way and I want it to be fairly easy to maintain.

Some approaches I have been thinking about:

1. Perform validation on a per instruction basis via a direct connection to another emulator, like Bochs.
2. Log the input and output of all executed instruction in VirtualXT and another emulator, then use a separate tool for detecting errors.
3. Build a hardware device that attaches a 8088 to the RaspberryPI's GPIO and perform validation on a per instruction basis. Kind of like nr. 1 but with real hardware.

I think the simplest approach would be nr 2. One option is [UniPCemu](https://superfury.itch.io/unipcemu). Superfury told me it already had some logging capabilities. But perhaps it is also possible to do in Bochs?

**Comment by lxyfish111** [comment]
Maybe, I understood a little about what you said.
You want a tool to check the instructions into the VirtualXT and the other emulator to find out the error instructions.
This is an interesting feature.

**Comment by razn-v** [comment]
Hi. I would like to work on this feature. I've been thinking of validating virtualxt against [86Box](https://github.com/86Box/86Box), a popular and active fork of PCem, however I'm confused about how the validator should act, here are some approaches I have in my mind:

1. The two emulators are simultaneously launched on a similar disk, and their outputs are compared at the same time. This would require synchronizing the emulators to execute the same thing?
2. Both virtualxt and 86Box "execute opcode" functions are modified to take a list of predefined opcodes that are given to them, then the outputs are written to a file and compared (or another way if the files are too large)
3. Same thing as 2. but with random opcodes

Which of these approaches would be the best? Maybe I'm completely missing the point?

**Comment by andreas-jonsson** [comment]
Hi! @razn-v,

Fantastic if you want to work on this! There are a few things that you should be aware of though. I'm working on a complete rewrite of the emulator. So it would be great if what ever solution is chosen that it is easily ported over to the new code once it is ready. I should also mention that I'm working on a hardware based validator for the new code base. However, contributing a software validator for the existing code base would still be greatly appreciated.

Having tried a few different approaches over the years I think the best solution would be no 2.

However, if you define the opcodes to be executed your self that would be more like the unit tests that are already part of the project.  (See **decode_test.go**) There is nothing wrong with that, but it is very time consuming and error prone to write those. :)

I think that you should try to configure the emulators to have as similar hardware as possible and then execute the same BIOS followed by a "userspace" application. On 8088/V20 systems the code path will likely be very similar and therefor the same code and data executed.

You can then write a standalone application to compare the different "logs" and point to anomalies together with debug information so the issue can be tracked down. You also need to account for undefined behavior. (That will be different between the emulators) For that you could make use of the **x86reference.xml** (included in the repo) and mask the flags that are to be compared or each opcode.

**Comment by razn-v** [comment]
Thanks for your response! 

I've already managed to replicate the same hardware on 86Box. However, I'm a bit concerned about these "logs" files, for example if I use the `-validator` flag from virtualxt, things get quickly to 10Gb without having even finished booting. Maybe I'm doing something wrong?

Anyway, thanks for the clarifications, I'll let you know my progress on my side.

**Comment by andreas-jonsson** [comment]
The validator code in VirtualXT is just for testing and it outputs to JSON. So by going to a compressed binary format you should easily reduce the size ~10 fold. So I think it should work.

You only need a few seconds of data and you might want to be able to enable it at runtime because as you say the boot up might not be so interesting.
