### ISSUE TITLE
Repeated int 0x8 before acknowledging the first

### ISSUE THREAD

**Issue by fmahnke** [andreas-jonsson/virtualxt#22]
This happens in the develop branch (93e4d85).

If I replace the BIOS int 0x8 handler with my own, and don't chain to the BIOS handler, vxt generates repeated int 0x8 interrupts even though I don't acknowledge the first one.

When the first int 0x8 interrupt comes, I expect to have to acknowledge it myself:

```
mov al,0x20
out 0x20,al
```

Or chain to BIOS handler, which does this for us.

But vxt appears to generate multiple int 0x8s on the timer tick, whether or not we acknowledge.

**Comment by andreas-jonsson** [comment]
This is indeed a bug in the PIC. Strange that it has not been discovered earlier?
@fmahnke Thanks for reporting this.

**Comment by andreas-jonsson** [comment]
Fixed in develop (b89c126dd08d52c5a68a605e2077b33feb716a4d)

Would be nice if this could be independently tested.

**Comment by fmahnke** [comment]
> This is indeed a bug in the PIC. Strange that it has not been discovered earlier?

I thought the same. My speculation was most finished and tested programs will expect that interrupt to happen reliably. Maybe there wouldn't be many cases where shipped software would intentionally disable it. I only noticed because I was developing.

**Comment by fmahnke** [comment]
> Fixed in develop ([b89c126](https://github.com/andreas-jonsson/virtualxt/commit/b89c126dd08d52c5a68a605e2077b33feb716a4d))
> 
> Would be nice if this could be independently tested.

Verified to work as expected in 5ffa9b.
