### ISSUE TITLE
Validator: WR and RD float on reset

### ISSUE THREAD

**Issue by dbalsom** [andreas-jonsson/virtualxt#30]
https://github.com/andreas-jonsson/virtualxt/blob/feecf2b4f30b516d9bee9797c356f28ec51d2084/tools/validator/pi8088/pi8088.c#L175

This assert fails on my particular 8088, as it seems both RD and WR read active-low until the first ALE.  Might be different on different revisions? My chip has a copyright date of 78 & 81

**Comment by andreas-jonsson** [comment]
I have two 80C88's from 78 that both work. However... I did find a V20 that shows this behavior. :) 
It is fixed in cff9edd3ca9e77141a7fe2985a31fb35f726af2c.

Thanks for reporting!
