### ISSUE TITLE
Flatpak release lags behind

### ISSUE THREAD

**Issue by shakeyourbunny** [andreas-jonsson/virtualxt#31]
Hi,

please update the  flatpak release, it is still 0.7.0, although 0.8.0 is current.

Thank you.

**Comment by andreas-jonsson** [comment]
Hi!

Yes, 0.7 is the latest "stable" build.
0.8 is not released yet and is work in progress. I will try to look in to providing an "edge" builds for flatpaks as well.

**Comment by andreas-jonsson** [comment]
Relates to #26

**Comment by andreas-jonsson** [comment]
This is now relevant with the 0.8 release.

**Comment by andreas-jonsson** [comment]
Updated to version 0.9
