### ISSUE TITLE
GLaBIOS as default

### ISSUE THREAD

**Issue by andreas-jonsson** [andreas-jonsson/virtualxt#44]
It would be nice to move to a actively maintained BIOS as default. GLaBIOS by @640-KB is a excellent alternative for this emulator.

Working through some of the issues here:

- [x] Build a custom version that accept the none standard FDC controller.
- [x] VGA module is corrupted on startup. Have noticed this when switching back to text mode.
- [x] MI demo runs way to slow. PIT issue?
- [x] Web version does not detect the COM port correctly. But the SDL version does?

**Comment by 640-KB** [comment]
Cool! Let me know if there's anything I can do to help.

**Comment by dbalsom** [comment]
GLaBIOS best BIOS

**Comment by andreas-jonsson** [comment]
It help's if mouse is actually enabled in the config for the web frontend.

@dbalsom rings a bell? :)

**Comment by andreas-jonsson** [comment]
Everything seems to work now. GLaBIOS will be default in upcoming release.
