### ISSUE TITLE
Rework RTC module

### ISSUE THREAD

**Issue by andreas-jonsson** [andreas-jonsson/virtualxt#45]
Update the RTC module so it can be used in the default config.
Possible ship with @640-KB's GLaTICK as default. (or a solutions that is actively maintained.)

**Comment by 640-KB** [comment]
What kind of chip does it use? DS12x85/MC146818? Should just work! :)

**Comment by andreas-jonsson** [comment]
It is suppose to be a MC146818. But it is not complete. :)

**Comment by andreas-jonsson** [comment]
Is done and GLaTICK will be part of the next release. It will be the default since GLaBIOS is also the default.
But the RTC module also work with TurboXT BIOS. :)

**Comment by 640-KB** [comment]
Awesome!  GLaBIOS is looking great on the live build.  I've added another link on the GLaBIOS site/GH page to it.  

Can't wait to see GLaTICK in the next release :)
