### ISSUE TITLE
EGA version of Commander Keen 4 shows garbage after configuration screen.

### ISSUE THREAD

**Issue by guest123guest** [andreas-jonsson/virtualxt#49]
![image](https://github.com/andreas-jonsson/virtualxt/assets/37600325/ad252a72-b585-4a0b-a2d1-33be7e6a24a9)
The configuration screen also doesn't seem to detect an emulated AdLib card. I haven't checked the CGA version.

Not sure if it's okay to share the game here, but I'll send a disk image of it if required. Otherwise, you should be able to track down the game and put it onto a 1.2 megabyte disk image.

Edit: Here's the configuration:
```
[modules]
chipset=xt
;cga=
disk=
adlib=
rifs=
ctrl=
joystick=0x201
ems=lotech_ems
mouse=0x3F8,4
;fdc=
;rtc=bios/GLaTICK_0.8.4_AT.ROM
;network=eth0
;arstech_isa=libarsusb4.so
;ch36x_isa=/dev/ch36xpci0
;lua=modules/lua/serial_debug.lua,0x3F8

; VGA module requires a 640K BIOS and CGA module to be disabled.
vga=bios/vgabios.bin

; GDB server module should always be loadad after the others.
; Otherwise you might have trouble with hardware breakpoints.
;gdb=1234

[args]
bios=bios/GLABIOS640.ROM
;halt=1
v20=0
;hdboot=1
;harddrive=boot/freedos_hd.img

[switch1]
ram=0x3
video=0x2
floppy=0x0

[ch36x_isa]
port=0x201

[arstech_isa]
port=0x201

[lotech_ems]
memory=0xD0000
port=0x260

[rifs]
port=0x178
```

**Comment by andreas-jonsson** [comment]
Hi!

Thank you for trying out VirtualXT!

Unfortunately I don't think you will get the EGA version working. VGA/EGA support is not complete.
Some Sierra games in mode 13 does work using an ET4000 VGA BIOS. But that is about all I'm afraid. :(
Only CGA (and Hercules mode with 640K BIOS) is supported atm. Sorry.

VGA will likely be the big addition in the upcoming 0.10 release.
You can track progress on VGA [here](https://github.com/andreas-jonsson/virtualxt/issues/5).

As for the Adlib issue. I have seen the same thing with Wolfenstein3D. It is not unlikely the detection routine is similar to Keen. It works by reading back some registers from the card. This specific operation is not supported in the current implementation. I will open a new issue for this. The solution is probably to switch from the current third-party OPL implementation to something more sophisticated.

**Comment by andreas-jonsson** [comment]
Here is the Adlib issue https://github.com/andreas-jonsson/virtualxt/issues/50

I will close this in favor of https://github.com/andreas-jonsson/virtualxt/issues/5
