### ISSUE TITLE
EGA/VGA Support

### ISSUE THREAD

**Issue by andreas-jonsson** [andreas-jonsson/virtualxt#5]
Add support for the most common EGA/VGA video modes.

- 320x200x16
- 640x350x16
- 320x200x256
- 640x480x16

**Comment by andreas-jonsson** [comment]
Some initial work has been done on 0.7 and it is a good starting point.

The lack of a opensource VGA BIOS for XT/AT systems needs to be addressed.
We could just accept that VGA support requires the user to supply there own BIOS but that is not ideal.

**Comment by shakeyourbunny** [comment]
See these projects for a open source BIOS:
- https://github.com/miurahr/vgabios
- https://www.seabios.org/SeaVGABIOS
- https://www.nongnu.org/vgabios/

Take one.

**Comment by shakeyourbunny** [comment]
But if you wanna do some period accurate VGA emulation there is no way around that requesting that the user has to provide a VGA ROM dump.

**Comment by andreas-jonsson** [comment]
Yes. I have been playing with those. It's been a while but as I recall they relied on 32bit instructions.
Since this is a XT (possible AT) emulator that wont work. But I will do another stab at it. :)

My goal is to provide the option of a out of the box solution but also maintain the possibility of using a old/real BIOS as well.

**Comment by andreas-jonsson** [comment]
A modified version of https://www.nongnu.org/vgabios/ without 32bit instructions are now included. :)

**Comment by andreas-jonsson** [comment]
Good enough for a first release. :)
