### ISSUE TITLE
Collection of ISA devices

### ISSUE THREAD

**Issue by andreas-jonsson** [andreas-jonsson/virtualxt#52]
It would be fun to have a large collection of ISA devices available.

- [x] Adlib card
- [x] Generic VGA card (https://github.com/andreas-jonsson/virtualxt/issues/5)
- [ ] Tandy Graphics (https://github.com/andreas-jonsson/virtualxt/issues/42)
- [ ] Tandy Audio (https://github.com/andreas-jonsson/virtualxt/issues/42)
- [ ] Soundblaster
- [ ] Diamond Trackstar (https://youtu.be/A-6AKe2pvsQ)
- [ ] Covox Speech Thing
- [ ] Disney Sound Source
- [ ] Gravis Ultrasound (Is there software support?)

...suggestions?

**Comment by stormyordos** [comment]
Gravis Ultrasound would be great if we're talking soundcards

**Comment by andreas-jonsson** [comment]
Never had one of those. Could be cool to try.
But are there any 8086/V20 software that supports it?

I realize there is not a lot of software that supports soundcards on these machines. :)

**Comment by stormyordos** [comment]
To be fair I had never heard of an XT system with an Adlib before, but back then I had a potato Amstrad PC-1512 :)

The "G-List" looks like a good resource for DOS games supporting Ultrasound, but as the card was first sold in '92 I doubt anything would work natively on a V20 or 8086: http://www.gravisultrasound.com/files/documentation/GLIST.TXT

**Comment by stormyordos** [comment]
For completeness's sake, I'd add the Pro Audio Spectrum and Media Vision Thunderboard sound cards

**Comment by andreas-jonsson** [comment]
Will split this in to separate issues.
