### ISSUE TITLE
GDB capabilities

### ISSUE THREAD

**Issue by fmahnke** [andreas-jonsson/virtualxt#60]
I don't think I used the previous debugger. I might've overlooked it. But I tried the new GDB stub today. Nice! Until now, the only other full-featured debugger I've had at the emulator level is in Bochs.

Is there a way to break the debugger when the breakpoint location is unknown before launching VXT? I normally do this in one of two ways.

Bochs supports an instruction called "magic breakpoint". If Bochs sees an `xchg bx,bx` instruction, which has no effect on the system state, it starts the debugger at that location. This is very convenient, but involves changing the code. I haven't seen this anywhere else, so maybe there are better methods. I'm open to suggestions.

If the breakpoint location can be determined at runtime, another method is to start the debugger at some arbitrary point, set the breakpoint, continue, and then invoke the code to be investigated. I tried this, but it didn't work:

- enable gdb in `config.ini`

```
[modules]
...
gdb=1234
```

- launch `virtualxt` as usual
- launch gdb with `gdb --init-command $VXT_SOURCE/modules/gdb/virtualxt.gdb`
    - press `c` to continue execution
    - press `^C` to interrupt execution

I get this message:

```
The target is not responding to interrupt requests.
Stop debugging it? (y or n)
```

Does VXT not yet support being interrupted by GDB?

**Comment by andreas-jonsson** [comment]
Unfortunately there is some limitation to how this stub is implemented so interruption form GDB is not possible.
This should be addressed at some point. The GDB module is a good candidate for rewriting in Lua.

However, there is a workaround. You can press Alt+F12 in VirtualXT (assuming GDB is attached) and it will cause an interrupt.

The previews debugger supported triggering the debugger from code by writing to an IO port.
You could even expand on this concept and allow for full control of the debugger from code. Setting breakpoints based on runtime state etc.

**Comment by andreas-jonsson** [comment]
@fmahnke You should now be able to interrupt from GDB instead of pressing Alt+F12 in VirtualXT.

You can also "interrupt" using the CTRL module by sending 0x0 followed by 0xA to port 0xB4. See the [emuctrl](https://github.com/andreas-jonsson/virtualxt/blob/develop/tools/emuctrl/emuctrl.c) tool.
